apiVersion: v1
kind: Service
metadata:
  name: blockchain-node-svc # Headless service for StatefulSet DNS resolution
  namespace: qr-auth
  labels:
    app: blockchain-node
spec:
  ports:
  - port: 5000
    name: http-node
    targetPort: http-node
  clusterIP: None # Makes it a headless service
  selector:
    app: blockchain-node # Selects the pods of the StatefulSet